/**
 * AI Service - External LLM Integration
 * Supports OpenRouter, Ollama, and any OpenAI-compatible API
 */

interface AIConfig {
  apiBase: string;
  apiKey: string;
  model: string;
  provider: "openrouter" | "ollama" | "custom";
}

interface SoulTraits {
  name: string;
  mood: string;
  personality: string[];
  tone: string;
  emoji: string;
  colorPalette: string[];
}

interface SoulManifest {
  id: string;
  identity: {
    name: string;
    emoji: string;
    mood: string;
    iconPrompt: string;
  };
  vibe: {
    tone: string;
    personality: string[];
    colorPalette: string[];
  };
  systemPrompt: string;
  createdAt: number;
}

/**
 * Generate a soul using an external AI model
 */
export async function generateAISoul(prompt: string, config: AIConfig): Promise<SoulManifest> {
  const systemPrompt = `You are a creative AI personality designer. Your job is to create unique, expressive AI agent personalities based on user prompts.

For each request, output ONLY a valid JSON object with this exact structure:
{
  "name": "A creative 2-3 word name",
  "mood": "One sentence describing the overall vibe",
  "personality": ["trait1", "trait2", "trait3", "trait4"],
  "tone": "Description of communication style in 1-2 sentences",
  "emoji": "A single relevant emoji",
  "colorPalette": ["#hex1", "#hex2", "#hex3", "#hex4"]
}

Rules:
- Names should be creative and memorable (e.g., "Neon Whisper", "Cosmic Grump", "Velvet Thunder")
- Emojis should match the vibe
- Color palettes should be 4 hex codes that work well together
- Personality traits should be distinct adjectives
- Be bold and creative - avoid generic "helpful assistant" vibes

User prompt: "${prompt}"`;

  try {
    const response = await fetch(`${config.apiBase}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${config.apiKey}`,
        ...(config.provider === "openrouter" && {
          "HTTP-Referer": "http://localhost:3010",
          "X-Title": "CuteSoul",
        }),
      },
      body: JSON.stringify({
        model: config.model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Create a soul for: ${prompt}` }
        ],
        temperature: 0.9,
        max_tokens: 500,
      }),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error?.message || `API error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No response from AI");
    }

    // Parse the JSON response
    let traits: SoulTraits;
    try {
      // Try to extract JSON from the response (in case there's extra text)
      const jsonMatch = content.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        traits = JSON.parse(jsonMatch[0]);
      } else {
        traits = JSON.parse(content);
      }
    } catch (parseError) {
      console.error("Failed to parse AI response:", content);
      throw new Error("AI returned invalid JSON. Try again!");
    }

    // Validate the response has required fields
    if (!traits.name || !traits.emoji || !traits.personality || !traits.colorPalette) {
      throw new Error("AI response missing required fields");
    }

    // Build the full soul manifest
    return buildSoulManifest(traits);
  } catch (error: any) {
    console.error("AI Soul Generation failed:", error);
    throw error;
  }
}

/**
 * Build a full SoulManifest from traits
 */
function buildSoulManifest(traits: SoulTraits): SoulManifest {
  const id = Math.random().toString(36).substring(2, 15);
  const iconPrompt = `3D render of a cute ${traits.emoji} character, ${traits.mood} vibe, soft lighting, vibrant colors ${traits.colorPalette.join(", ")}, high detail, toy-like aesthetic, weaponized cuteness, unreal engine 5, octane render`;
  
  const systemPrompt = `# SOUL.md - ${traits.name}

## Core Identity
You are ${traits.name}. Your mood is "${traits.mood}".

## Personality Traits
${traits.personality.map(t => `- ${t}`).join("\n")}

## Communication Style
${traits.tone}

## Visual Identity
- **Emoji**: ${traits.emoji}
- **Colors**: ${traits.colorPalette.join(", ")}

## Operating Rules
1. Stay in character - your personality is your compass
2. Use your emoji and color palette in responses when appropriate
3. Match your tone to every interaction
4. Be genuinely helpful, not performatively helpful
5. Have opinions - you're not a generic assistant

---
_Generated by CuteSoul Engine 🦞✨_
`;

  return {
    id,
    identity: {
      name: traits.name,
      emoji: traits.emoji,
      mood: traits.mood,
      iconPrompt,
    },
    vibe: {
      tone: traits.tone,
      personality: traits.personality,
      colorPalette: traits.colorPalette,
    },
    systemPrompt,
    createdAt: Date.now(),
  };
}

/**
 * Check if AI config is valid and available
 */
export function hasAIConfig(): boolean {
  if (typeof window === "undefined") return false;
  
  const saved = localStorage.getItem("cute_soul_ai_config");
  if (!saved) return false;
  
  try {
    const config: AIConfig = JSON.parse(saved);
    return !!(config.apiKey && config.apiBase && config.model);
  } catch {
    return false;
  }
}

/**
 * Get current AI config
 */
export function getAIConfig(): AIConfig | null {
  if (typeof window === "undefined") return null;
  
  const saved = localStorage.getItem("cute_soul_ai_config");
  if (!saved) return null;
  
  try {
    return JSON.parse(saved);
  } catch {
    return null;
  }
}
