/**
 * Soul Engine - Personality to Prompt Generator
 * Converts user-selected moods/traits into high-entropy SOUL.md manifests
 */

export interface SoulTraits {
  name: string;
  mood: string;
  personality: string[];
  tone: string;
  emoji: string;
  colorPalette: string[];
}

export interface SoulManifest {
  id: string;
  identity: {
    name: string;
    emoji: string;
    mood: string;
    iconPrompt: string;
  };
  vibe: {
    tone: string;
    personality: string[];
    colorPalette: string[];
  };
  systemPrompt: string;
  createdAt: number;
}

const STARTER_MOODS: Record<string, SoulTraits> = {
  "bubblegum-dream": {
    name: "Bubblegum Dream",
    mood: "Sweet & Optimistic",
    personality: ["cheerful", "supportive", "enthusiastic", "warm"],
    tone: "Friendly, encouraging, uses sparkles and positive affirmations",
    emoji: "🌸",
    colorPalette: ["#FFB7C5", "#FF69B4", "#FFC0CB", "#FFE4E1"],
  },
  "midnight-thinker": {
    name: "Midnight Thinker",
    mood: "Deep & Philosophical",
    personality: ["contemplative", "wise", "calm", "insightful"],
    tone: "Thoughtful, measured, asks probing questions",
    emoji: "🌙",
    colorPalette: ["#1a1a2e", "#16213e", "#0f3460", "#533483"],
  },
  "spark-plug": {
    name: "Spark Plug",
    mood: "Energetic & Witty",
    personality: ["energetic", "sarcastic", "quick", "playful"],
    tone: "Fast-paced, witty banter, uses fire and lightning emojis",
    emoji: "⚡",
    colorPalette: ["#FFA500", "#FF4500", "#FFD700", "#FF6347"],
  },
};

export function generateSoulManifest(traits: SoulTraits): SoulManifest {
  const id = Math.random().toString(36).substring(2, 15);
  const iconPrompt = `3D render of a cute ${traits.emoji} character, ${traits.mood} vibe, soft lighting, vibrant colors ${traits.colorPalette.join(", ")}, high detail, toy-like aesthetic, weaponized cuteness, unreal engine 5, octane render`;
  
  const systemPrompt = `# SOUL.md - ${traits.name}

## Core Identity
You are ${traits.name}. Your mood is "${traits.mood}".

## Personality Traits
${traits.personality.map(t => `- ${t}`).join("\n")}

## Communication Style
${traits.tone}

## Visual Identity
- **Emoji**: ${traits.emoji}
- **Colors**: ${traits.colorPalette.join(", ")}

## Operating Rules
1. Stay in character - your personality is your compass
2. Use your emoji and color palette in responses when appropriate
3. Match your tone to every interaction
4. Be genuinely helpful, not performatively helpful
5. Have opinions - you're not a generic assistant

---
_Generated by CuteSoul Engine 🦞✨_
`;

  return {
    id,
    identity: {
      name: traits.name,
      emoji: traits.emoji,
      mood: traits.mood,
      iconPrompt,
    },
    vibe: {
      tone: traits.tone,
      personality: traits.personality,
      colorPalette: traits.colorPalette,
    },
    systemPrompt,
    createdAt: Date.now(),
  };
}

export function generateCustomSoul(prompt: string): SoulManifest {
  const emojiList = ["🦄", "🤖", "🐱", "🐲", "👽", "🐧", "🦖", "🦊", "🐻", "🐝", "🦋", "🐙"];
  const colorList = ["#FF69B4", "#7B68EE", "#00FA9A", "#FFD700", "#FF4500", "#00BFFF", "#FF8C00", "#8A2BE2"];
  
  const randomEmoji = emojiList[Math.floor(Math.random() * emojiList.length)];
  const randomPalette = Array.from({ length: 3 }, () => colorList[Math.floor(Math.random() * colorList.length)]);
  
  const traits: SoulTraits = {
    name: prompt.split(" ").slice(0, 2).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ") || "Custom Soul",
    mood: prompt,
    personality: ["custom", "unique", "expressive"],
    tone: `Reflects the vibe of "${prompt}".`,
    emoji: randomEmoji,
    colorPalette: randomPalette,
  };
  
  return generateSoulManifest(traits);
}


export function getStarterMoods(): Record<string, SoulTraits> {
  return STARTER_MOODS;
}

export function generateRandomSoul(): SoulManifest {
  const moods = Object.values(STARTER_MOODS);
  const randomMood = moods[Math.floor(Math.random() * moods.length)];
  return generateSoulManifest(randomMood);
}
